### ISSUE TITLE
Can't build a C++ "Hello world" program

### ISSUE THREAD

**Issue by zhuowei** [CraneStation/wasi-sdk#21] opened 2019-04-18 03:38 UTC
I can't compile a simple C++ hello world program with sdk 3.0 on Linux.

I tried compiling this:

```
#include <iostream>

int main() {
	std::cout << "Hello world!" << std::endl;
}
```

But it fails to link due to missing pthreads functions used by libc++:

https://gist.github.com/zhuowei/fc4c13962057a674692f3e6048d547ac

A C hello world program does build and run (using the in-browser polyfill), so my SDK install seems fine.

Is there a compiler/linker parameter I need to add so these functions would link?

Edit: I'm assuming #12 would help? Do I need to build the wasi-sdk from source to get that patch, or should I wait for the next wasi-sdk release?

**Comment by kubkon** [comment] 2019-04-18 09:37
I can confirm that all of the errors related to `pthreads` are resolved with the latest version in master. So yeah, if you build from source, that's handled. However, there still is a problem with symbols related to exception handling in C++ missing:

```
cpp-test ) /opt/wasi-sdk/bin/clang++ main.cpp -v
clang version 8.0.0 
Target: wasm32-unknown-wasi
Thread model: single
InstalledDir: /opt/wasi-sdk/bin
 "/opt/wasi-sdk/bin/clang-8" -cc1 -triple wasm32-unknown-wasi -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name main.cpp -mrelocation-model static -mthread-model single -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu generic -fvisibility hidden -dwarf-column-info -debugger-tuning=gdb -momit-leaf-frame-pointer -v -resource-dir /opt/wasi-sdk/lib/clang/8.0.0 -isysroot /opt/wasi-sdk/share/sysroot -internal-isystem /opt/wasi-sdk/share/sysroot/include/wasm32-wasi/c++/v1 -internal-isystem /opt/wasi-sdk/share/sysroot/include/c++/v1 -internal-isystem /opt/wasi-sdk/share/sysroot/include/wasm32-wasi -internal-isystem /opt/wasi-sdk/share/sysroot/include -fdeprecated-macro -fdebug-compilation-dir /home/jakubkonka/dev/cpp-test -ferror-limit 19 -fmessage-length 118 -fobjc-runtime=gnustep -fcxx-exceptions -fexceptions -fno-common -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/main-a3125e.o -x c++ main.cpp
clang -cc1 version 8.0.0 based upon LLVM 8.0.0 default target wasm32-unknown-wasi
ignoring nonexistent directory "/opt/wasi-sdk/share/sysroot/include/wasm32-wasi/c++/v1"
ignoring nonexistent directory "/opt/wasi-sdk/share/sysroot/include/wasm32-wasi"
ignoring nonexistent directory "/opt/wasi-sdk/share/sysroot/usr/local/include"
ignoring nonexistent directory "/opt/wasi-sdk/share/sysroot/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/wasi-sdk/share/sysroot/include/c++/v1
 /opt/wasi-sdk/share/sysroot/include
 /opt/wasi-sdk/lib/clang/8.0.0/include
End of search list.
 "/opt/wasi-sdk/bin/wasm-ld" -L/opt/wasi-sdk/share/sysroot/lib/wasm32-wasi /opt/wasi-sdk/share/sysroot/lib/wasm32-wasi/crt1.o /tmp/main-a3125e.o -lc++ -lc++abi -lc /opt/wasi-sdk/lib/clang/8.0.0/lib/wasi/libclang_rt.builtins-wasm32.a -o a.out
wasm-ld: warning: function signature mismatch: _ZNSt3__215basic_streambufIcNS_11char_traitsIcEEE7seekoffExNS_8ios_base7seekdirEj
>>> defined as (i32, i32, i64, i32, i32) -> void in /opt/wasi-sdk/share/sysroot/lib/wasm32-wasi/libc++.a(ios.cpp.obj)
>>> defined as () -> void in /opt/wasi-sdk/share/sysroot/lib/wasm32-wasi/libc++.a(iostream.cpp.obj)

wasm-ld: warning: function signature mismatch: _ZNSt3__215basic_streambufIcNS_11char_traitsIcEEE7seekposENS_4fposI11__mbstate_tEEj
>>> defined as (i32, i32, i32, i32) -> void in /opt/wasi-sdk/share/sysroot/lib/wasm32-wasi/libc++.a(ios.cpp.obj)
>>> defined as () -> void in /opt/wasi-sdk/share/sysroot/lib/wasm32-wasi/libc++.a(iostream.cpp.obj)

wasm-ld: warning: function signature mismatch: _ZNSt3__215basic_streambufIwNS_11char_traitsIwEEE7seekoffExNS_8ios_base7seekdirEj
>>> defined as (i32, i32, i64, i32, i32) -> void in /opt/wasi-sdk/share/sysroot/lib/wasm32-wasi/libc++.a(ios.cpp.obj)
>>> defined as () -> void in /opt/wasi-sdk/share/sysroot/lib/wasm32-wasi/libc++.a(iostream.cpp.obj)

wasm-ld: warning: function signature mismatch: _ZNSt3__215basic_streambufIwNS_11char_traitsIwEEE7seekposENS_4fposI11__mbstate_tEEj
>>> defined as (i32, i32, i32, i32) -> void in /opt/wasi-sdk/share/sysroot/lib/wasm32-wasi/libc++.a(ios.cpp.obj)
>>> defined as () -> void in /opt/wasi-sdk/share/sysroot/lib/wasm32-wasi/libc++.a(iostream.cpp.obj)

wasm-ld: error: /tmp/main-a3125e.o: undefined symbol: __cxa_begin_catch
clang-8: error: lld command failed with exit code 1 (use -v to see invocation)
```

**Comment by pchickey** [comment] 2019-04-18 18:00
Correct - WebAssembly does not yet have support for exceptions, so clang++ requires the `-fno-exceptions` flag to be passed. It also does not yet have support for threads, which #12 addresses in the build of the standard library.

**Closed by pchickey** 2019-04-18 18:00 UTC

**Comment by sunfishcode** [comment] 2019-04-24 21:27
As a quick addendum here, the function signature mismatch warnings are due to https://bugs.llvm.org/show_bug.cgi?id=40412 and are harmless in this context. And, WASI support for C++ exceptions is waiting for [support in WebAssembly](https://github.com/WebAssembly/exception-handling/).
